name: productcatalogservice
description: The productcatalogservice of the online boutique by Google
componentType: Kubernetes Container
properties:
  prometheus:
    job: .*
    instance: .*
    name: .*
    pod: ak-productcatalogservice.*
    container: server